### ISSUE TITLE
Think about releasing

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz-web#178]

**Comment by escapedcat** [comment]
Suggestion/idea:  

- https://www.conventionalcommits.org  
  > A specification for adding human and machine readable meaning to commit messages.
- https://github.com/conventional-changelog/standard-version
  > A utility for versioning using semver and CHANGELOG generation powered by Conventional Commits.
- https://commitlint.js.org
  > commitlint checks if your commit messages meet the conventional commit format.
