### ISSUE TITLE
ModalDialog: show header on top

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz-web#413]
Currently, the header is centered with the content in the ModalDialog, as shown here:

https://github.com/cstenglein/raspiblitz-web/pull/412

Place the header on top & have the content centered, should look better IMO

**Comment by escapedcat** [comment]
Something in the direction of this?
<img width="634" alt="image" src="https://github.com/cstenglein/raspiblitz-web/assets/1016218/b3efab6d-3237-45b4-9c83-b16fee466964">

Could also think about adding i.e. these components:
- https://headlessui.com/react/dialog
- https://tailwindui.com/components/application-ui/overlays/modals

**Comment by cstenglein** [comment]
Yes 👍

**Comment by escapedcat** [comment]
I think this can be closed
