### ISSUE TITLE
RaspiBlitz: 1.9.0 WebUI: 1.1.0 LNBits onion url misformed

### ISSUE THREAD

**Issue by jalbstmeijer** [raspiblitz/raspiblitz-web#630]
When on the onion url of RaspiBlitz, LNBits is linked as https://{raspiublitz_url}.onion/{lnbits_url}.onion instead of http://{lnbits_url}.onion

**Comment by cstenglein** [comment]
@rootzoll Looks at first look like the wrong url is in redis

**Comment by rootzoll** [comment]
@cstenglein I dont see redis in play here. For me this looks like the WebUI is creating the wrong url formatting in the end. 

The way it goes is: The API calls the script `bonus.lnbits.sh status` takes the `toraddress` from there and gives it out as the `hiddenService` for the lnbits app. And in your example above this looks correct. But when calling the WebUI thru TorBrowser with the WebUI-Onion, then going to the APP section and wanna opening lnbits - I also see a `https://{raspiublitz_url}.onion/{lnbits_url}.onion` style address which does not work.

**Comment by cstenglein** [comment]
@rootzoll thank you for clarifying, looks like I didn't understand the issue at first.

Got a fix ready, will push soon.
