### ISSUE TITLE
Let users connect to Alby directly from the Web UI

### ISSUE THREAD

**Issue by MoritzKa** [raspiblitz/raspiblitz-web#632]
Alby is already part of the CONNECT section if you log into the RaspiBlitz via SSH. 
It would be great if users have the chance to connect to Alby directly via the new Web UI. 

The new addAccounts() APIs make that possible and allow users to programmatically add accounts to Alby. 

You can find the docs over here: https://guides.getalby.com/alby-extension-apis/

Albys extension APIs are provided via the window.alby object (very much like [WebLN](https://www.webln.guide/)). You don't need to add any dependencies or packages to your project.

The user is forwarded to getalby.com if the hasn't installed Alby yet.

**Comment by escapedcat** [comment]
Heyhey, does this duplicate #207 ?

**Comment by MoritzKa** [comment]
It is a more user friendly way to connect Alby: No need to c/p macaroons anymore.

**Comment by MoritzKa** [comment]
https://github.com/fusion44/blitz_api/pull/86 seems to provide the necessary data: macaroon and REST API host.
- Shall we close https://github.com/cstenglein/raspiblitz-web/issues/207 and use this issue for the discussion. We basically don't need a UI anymore except a button as shown in the demo on: https://guides.getalby.com/alby-extension-apis/

**Comment by MoritzKa** [comment]
What can a non-developer like me do to help?

**Comment by escapedcat** [comment]
@MoritzKa have a look at #640

**Comment by escapedcat** [comment]
LND connext is merged. [CLN could be done later after open points are solved](https://github.com/raspiblitz/raspiblitz-web/pull/640#issuecomment-1637300183).
