### ISSUE TITLE
MyNode to Raspiblitz

### ISSUE THREAD

**Issue by PerpetualWar** [raspiblitz/raspiblitz-web#654]
I had MyNode installed previously with full blockchain downloaded, no lightning set.

Decided to switch to raspiblitz, did migration as raspiblitz suggested, and now Im stuck at node syncing screen, block chain progress is 100%, have peers connected, lightning progress is in prepare sync. 

Not sure what am I waiting to sync if I already have blockchain completely synced.

I did one reboot to see if it will move things up, but nothing happens. it is like that for at least 24 hours if not more. 

On top of it it crashed with this message just now on the web client: 
```
Stack trace:

at U_ (http://192.168.31.38/assets/index-b1052a2a.js:84:4259) at j1 (http://192.168.31.38/assets/index-b1052a2a.js:58:6136) at M1 (http://192.168.31.38/assets/index-b1052a2a.js:67:713) at L2 (http://192.168.31.38/assets/index-b1052a2a.js:86:18317) at a (http://192.168.31.38/assets/index-b1052a2a.js:68:3231)
```
Can I make it work without formatting disk and all the data, which took around 4 days to download (for MyNode at the time)?

In the end I could do that as well, if that is necessary.  Just dunno how to restart whole setup now.

Help appreciated.

**Comment by cstenglein** [comment]
Try to delete your browser cache please :)

**Comment by cstenglein** [comment]
As discussed in https://github.com/raspiblitz/raspiblitz/issues/4155 was tested and worked with v1.11.0rc2 and worked. :)
