### ISSUE TITLE
Setup Redesign

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz-web#698]
This collects all issues regarding the setup redesign

- [x] #699 
- [x] #700 
- [x] #701 
- [x] #702 
- [x] #703 
- [x] #704 
- [x] #705 
- [x] #706 
- [x] #707 
- [x] #708 
- [x] #711 
- [x] #732 
---
Afterwards: 
- [ ] #725

**Comment by cstenglein** [comment]
Mockup for Cancel:

![grafik](https://github.com/raspiblitz/raspiblitz-web/assets/9399034/0cc62762-6b15-4bd3-835e-12508afe72e8)

**Comment by cstenglein** [comment]
Yes we can just use that as well if not possible.

Stacked is better for mobile & is consistent with the current styling IMO but should work either way :)

**Comment by escapedcat** [comment]
Got it, let's see

**Comment by escapedcat** [comment]
We might want to create a headline component to not repeat styles
<img width="171" alt="image" src="https://github.com/raspiblitz/raspiblitz-web/assets/1016218/2f498162-f461-4fb2-adaf-bfeef4dccb07">
<img width="164" alt="image" src="https://github.com/raspiblitz/raspiblitz-web/assets/1016218/1ff7341d-54f8-4d73-8d03-9128856f3b82">
<img width="175" alt="image" src="https://github.com/raspiblitz/raspiblitz-web/assets/1016218/f40e2f9c-762f-41fa-8cf1-22318f5d6db5">
etc
