### ISSUE TITLE
Setup Redesign: LightningDialog.tsx

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz-web#702]
![grafik](https://github.com/raspiblitz/raspiblitz-web/assets/9399034/3f9df824-bdb7-42c4-b1cc-2c1e9095a621)

![grafik](https://github.com/raspiblitz/raspiblitz-web/assets/9399034/ba02a79c-00b5-4d55-805e-632d0028fc3a)

**Comment by rootzoll** [comment]
Maybe order "Bitcoin only" first and then the others. 

Thsi is what ChatGPT would provide as explainers:

Running a Bitcoin full node can vary significantly depending on whether you add Lightning functionality and which implementation you choose. Here are brief explainers on running a Bitcoin full node without Lightning, with the Lightning Network Daemon (LND) implementation, and with the Core Lightning (CLN) implementation:

### 1. Bitcoin Full Node Without Lightning
Running a Bitcoin full node without any Lightning Network implementation involves participating directly in the Bitcoin network by validating transactions and blocks. Such a node contributes to the Bitcoin network's security and robustness and ensures privacy and full control over transactions. This setup, however, doesn't support instant transactions or microtransactions, as it relies solely on the traditional Bitcoin blockchain operations, which can be slower and incur higher fees during peak times.

### 2. Bitcoin Full Node with Lightning LND Implementation
Adding the Lightning Network Daemon (LND), developed by Lightning Labs, to a Bitcoin full node introduces capabilities for faster and cheaper transactions. LND is one of the most popular and user-friendly implementations of the Lightning Network, providing tools and features that facilitate creating and managing payment channels. This setup enhances a Bitcoin full node by allowing it to participate in both the underlying blockchain and a layer-2 solution, which significantly speeds up transactions while reducing costs, ideal for microtransactions.

### 3. Bitcoin Full Node with Core Lightning Implementation
Core Lightning (formerly known as c-lightning) is a Lightning Network implementation by Blockstream focused on performance and extendibility for developers and advanced users. Running a Bitcoin full node with Core Lightning offers high levels of customization and is designed to be modular, making it suitable for developers looking to build and deploy complex products and services on top of it. CLN is well-suited for users with technical expertise who are interested in exploring experimental features and optimizing the node’s performance in the Lightning Network.
