### ISSUE TITLE
Setup Redesign: WaitScreen.tsx

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz-web#704]
Mockup:

![grafik](https://github.com/raspiblitz/raspiblitz-web/assets/9399034/0f951199-7665-4748-b73d-1f208d1ffa72)

**Comment by escapedcat** [comment]
Suggesting to use a styled default:
https://nextui.org/docs/components/progress

**Comment by cstenglein** [comment]
Yes let's use that instead :)

We could also use a Spinner:  https://nextui.org/docs/components/spinner

**Comment by escapedcat** [comment]
Progress can be used here then:
<img width="410" alt="image" src="https://github.com/raspiblitz/raspiblitz-web/assets/1016218/7c67da30-46aa-4c99-b2a3-de6fb02298ca">
