### ISSUE TITLE
Setup Redesign: SyncScreen.tsx

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz-web#706]
![grafik](https://github.com/raspiblitz/raspiblitz-web/assets/9399034/de3d6f59-a25a-44e7-8cf0-3ea1c236de94)

**Comment by escapedcat** [comment]
What bout the wallet unlock? Has it been moved?
<img width="2106" alt="image" src="https://github.com/raspiblitz/raspiblitz-web/assets/1016218/93ec99e9-4cb8-49d1-ba32-49c9f556eb60">
