### ISSUE TITLE
[v1.11.4rc1] WebUI not able to show Apps

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz-web#805]
Running on RaspiBlitz image v1.11.4rc1 - API has already merged changes from fusion and WebUI is still on `release/v1.11`

```
admin@192.168.178.143:~ ₿ ./config.scripts/blitz.web.ui.sh info
installed=1
repo='https://github.com/raspiblitz/raspiblitz-web.git'
branch='release/v1.11'
commit='9f11772c17d7a676482d733334faf671eb7f8b83'
```

Dashboard loads, but when I click on "Apps" in sidebar I get:

![Bildschirmfoto 2024-12-18 um 23 04 18](https://github.com/user-attachments/assets/dea42763-271e-4aea-96eb-04b0de592b7e)

**Comment by escapedcat** [comment]
Weird, could you add a screenshot with opened dev-tools on "network" and "console"?

**Comment by rootzoll** [comment]
Seems fixed with the latest WebUI able to handle AlbyHub. Closing.
